"use client";
import "./report.css";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Check, ChevronDown, Copy, Download, Home, Image as ImageIcon, RotateCcw, Sparkles, X } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Mascot } from "@/components/mascot";
import { DISCLAIMER, SHORT_DISCLAIMER } from "@/lib/constants";
import { loadChart, loadReport, STORAGE } from "@/lib/storage";
import type { BaziChart, ElementKey } from "@/types/bazi";
import type { BaziReport } from "@/types/report";

const elements:Record<ElementKey,{name:string,desc:string}>={wood:{name:"木",desc:"象征成长、延展、规划和适应能力。"},fire:{name:"火",desc:"象征热情、表达、行动和可见度。"},earth:{name:"土",desc:"象征稳定、承载、现实感和持续性。"},metal:{name:"金",desc:"象征边界、规则、判断和精炼能力。"},water:{name:"水",desc:"象征流动、洞察、联想和应变能力。"}};
export default function ReportPage(){const router=useRouter();const [report,setReport]=useState<BaziReport|null>(null);const [chart,setChart]=useState<BaziChart|null>(null);const [share,setShare]=useState(false);const [sample,setSample]=useState(false);const [active,setActive]=useState<ElementKey>("wood");
  useEffect(()=>{
    const r=loadReport(),c=loadChart();
    if(!r||!c){router.replace("/");return}
    // 报告只在客户端会话中存在，挂载后读取一次。
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setReport(r);setChart(c);setSample(new URLSearchParams(location.search).get("sample")==="1"||sessionStorage.getItem(STORAGE.sample)==="true");
  },[router]);
  if(!report||!chart)return <main className="app-shell paper-grain loading-page">正在展开报告…</main>;
  const pillars=[ ["年柱",chart.pillars.year],["月柱",chart.pillars.month],["日柱",chart.pillars.day],["时柱",chart.pillars.hour] ] as const;
  return <main className="app-shell paper-grain report-page"><PageHeader title="文化体验报告"/><div className="report-notice">结果仅供参考，请理性阅读</div><div className="content report-content">{sample&&<div className="sample-banner">以下为虚构示例，不对应真实个人。</div>}
    <section className="report-cover card"><p className="section-kicker">PERSONAL CULTURAL PORTRAIT</p><h1>{report.title}</h1><p>{report.subtitle}</p><div className="pillar-inline">{pillars.map(([name,p])=><span key={name}>{p?p.display:"未定"}</span>)}</div><div className="keyword-row">{report.summary.coreKeywords.slice(0,5).map(x=><b key={x}>{x}</b>)}</div><div className="cover-meta"><span>准确度 · {{high:"高",medium:"中",low:"低"}[chart.confidence.level]}</span><span>{new Date().toLocaleDateString("zh-CN")}</span></div><i className="cover-seal">观</i></section>
    <p className="top-disclaimer">本报告是传统文化体验，不属于科学预测，也不应作为重大人生决策依据。</p><Mascot text="把有共鸣的部分留下，把不符合你的部分当作一种文化观察就好。"/>
    <ReportSection eyebrow="开卷" title="一眼看见你的命盘气质"><p>{report.summary.opening}</p><p className="confidence-note"><Sparkles size={16}/>{report.summary.confidenceNotice}</p></ReportSection>
    <ReportSection eyebrow="四柱" title="命盘结构总览"><div className="pillars">{pillars.map(([name,p])=><article key={name} className={!p?"unknown":""}><span>{name}</span>{p?<><b>{p.heavenlyStem}</b><b>{p.earthlyBranch}</b></>:<><b>未</b><b>定</b></>}</article>)}</div>{chart.pillars.hourCandidates&&<p className="candidate">候选时柱：{chart.pillars.hourCandidates.map(x=>x.display).join("、")}，差异内容已降低分析强度。</p>}<div className="overview-copy"><p>{report.chartOverview.dayMasterExplanation}</p><p>{report.chartOverview.structureSummary}</p></div></ReportSection>
    <ReportSection eyebrow="五行" title="五行分布"><div className="element-chart"><div className="flower">{(Object.keys(elements) as ElementKey[]).map((k,i)=><button key={k} className={`${k} ${active===k?"active":""}`} style={{"--i":i,"--scale":.55+chart.fiveElements[k]/100} as React.CSSProperties} onClick={()=>setActive(k)}><b>{elements[k].name}</b><small>{chart.fiveElements[k]}%</small></button>)}<span>{chart.dayMaster.stem}<small>日主</small></span></div><div className="legend">{(Object.keys(elements) as ElementKey[]).map(k=><button key={k} className={active===k?"active":""} onClick={()=>setActive(k)}><i className={k}/>{elements[k].name}</button>)}</div></div><div className="element-explain"><b>{elements[active].name}的文化象征</b><p>{elements[active].desc}这是一种文化象征，不等同于心理测评结论。</p></div><p>{report.chartOverview.fiveElementsExplanation}</p></ReportSection>
    <ReportSection eyebrow="性格" title={report.personality.title}><p>{report.personality.summary}</p><ListBlock title="可能优势" items={report.personality.strengths}/><ListBlock title="值得留意" items={report.personality.possibleChallenges}/><ListBlock title="给自己的问题" items={report.personality.reflectionQuestions} question/></ReportSection>
    <ReportSection eyebrow="能力" title={report.abilities.title}><p>{report.abilities.summary}</p><ListBlock title="潜在优势" items={report.abilities.potentialStrengths}/><ListBlock title="发展建议" items={report.abilities.developmentSuggestions}/></ReportSection>
    <ReportSection eyebrow="事业" title={report.career.title}><p>{report.career.summary}</p><ListBlock title="更舒服的工作方式" items={report.career.suitableWorkStyles}/><ListBlock title="可探索的环境" items={report.career.possibleDirections}/><p className="caution">{report.career.caution}</p></ReportSection>
    <ReportSection eyebrow="资源" title={report.wealth.title}><p>{report.wealth.summary}</p><ListBlock title="可能模式" items={report.wealth.possiblePatterns}/><ListBlock title="现实建议" items={report.wealth.practicalSuggestions}/><p className="caution">{report.wealth.caution}</p></ReportSection>
    <ReportSection eyebrow="关系" title={report.relationships.title}><p>{report.relationships.summary}</p><ListBlock title="沟通倾向" items={report.relationships.communicationPatterns}/><ListBlock title="相处建议" items={report.relationships.relationshipSuggestions}/></ReportSection>
    <ReportSection eyebrow="成长" title={report.growth.title}><p>{report.growth.summary}</p><ListBlock title="当下重点" items={report.growth.currentFocus}/><ListBlock title="可以立刻开始" items={report.growth.actionableSuggestions}/></ReportSection>
    {report.focusAreaInsights.length>0&&<ReportSection eyebrow="你关心的" title="关注方向补充">{report.focusAreaInsights.map(x=><details key={x.area} className="insight"><summary>{x.area}<ChevronDown size={17}/></summary><p>{x.insight}</p><ul>{x.suggestions.map(s=><li key={s}>{s}</li>)}</ul></details>)}</ReportSection>}
    <section className="closing card"><i>观</i><h2>{report.finalMessage.easternStyleSentence}</h2><p>{report.finalMessage.practicalClosing}</p></section><div className="final-disclaimer"><b>理性阅读说明</b><p>{report.disclaimer||DISCLAIMER}</p></div>
    <div className="report-actions"><button className="primary-button" onClick={()=>setShare(true)}><ImageIcon size={18}/>生成我的东方人格卡</button><div><Link href="/input" onClick={()=>{sessionStorage.removeItem(STORAGE.request);sessionStorage.removeItem(STORAGE.sample)}} className="secondary-button"><RotateCcw size={17}/>再测一次</Link><Link href="/" className="secondary-button"><Home size={17}/>返回首页</Link></div></div>
  </div>{share&&<ShareModal report={report} chart={chart} onClose={()=>setShare(false)}/>}</main>}

function ReportSection({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="report-section card"><p className="section-kicker">{eyebrow}</p><h2>{title}</h2><div className="report-body">{children}</div></section>}
function ListBlock({title,items,question=false}:{title:string;items:string[];question?:boolean}){return <div className={`list-block ${question?"questions":""}`}><h3>{title}</h3><ul>{items.map((x,i)=><li key={x}><span>{question?"问":String(i+1).padStart(2,"0")}</span>{x}</li>)}</ul></div>}
function ShareModal({report,chart,onClose}:{report:BaziReport;chart:BaziChart;onClose:()=>void}){const ref=useRef<HTMLDivElement>(null);const [busy,setBusy]=useState(false);const [copied,setCopied]=useState(false);async function save(){if(!ref.current)return;setBusy(true);try{const html2canvas=(await import("html2canvas")).default;const canvas=await html2canvas(ref.current,{scale:2,backgroundColor:"#F7F0E3",useCORS:true});const a=document.createElement("a");a.download=`东方人格卡-${Date.now()}.png`;a.href=canvas.toDataURL("image/png");a.click()}finally{setBusy(false)}}async function copy(){await navigator.clipboard.writeText(location.origin);setCopied(true);setTimeout(()=>setCopied(false),1500)}return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="东方人格分享卡"><div className="share-modal"><button className="modal-close" aria-label="关闭" onClick={onClose}><X/></button><div className="share-card" ref={ref}><div className="share-brand"><span className="seal-mini">东</span><b>东方命盘</b></div><p className="section-kicker">我的东方人格卡</p><div className="share-orbit"><span>{chart.dayMaster.stem}</span></div><div className="share-keywords">{report.summary.coreKeywords.slice(0,3).map(x=><b key={x}>{x}</b>)}</div><blockquote>{report.finalMessage.easternStyleSentence}</blockquote><div className="qr-placeholder">访问<br/>二维码</div><small>{new Date().toLocaleDateString("zh-CN")} · {SHORT_DISCLAIMER}</small></div><p className="share-privacy">分享卡默认隐藏生日、时间、地点、性别及完整命盘。{SHORT_DISCLAIMER}</p><div className="share-buttons"><button className="primary-button" onClick={save} disabled={busy}><Download size={17}/>{busy?"正在生成…":"保存图片"}</button><button className="secondary-button" onClick={copy}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?"已复制":"复制分享链接"}</button></div></div></div>}
