"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Clock3, Globe2, MapPin, Pencil, UserRound } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Mascot } from "@/components/mascot";
import { CN_LOCATIONS, DEFAULT_BIRTH_INFO, DISCLAIMER, FOCUS_AREAS, PERIODS, SHICHEN } from "@/lib/constants";
import { loadBirth, saveJson, STORAGE } from "@/lib/storage";
import { birthInfoSchema } from "@/lib/validation/birth-info";
import type { BirthInfo, CalendarType, Gender, TimeAccuracy } from "@/types/birth";

const timeLabels={exact:"精确",shichen:"大致准确",period:"仅知时间段",unknown:"时间未知"};
export default function InputPage(){
  const router=useRouter(); const [step,setStep]=useState(1); const [error,setError]=useState("");
  const [data,setData]=useState<BirthInfo>({...DEFAULT_BIRTH_INFO, focusAreas:[...DEFAULT_BIRTH_INFO.focusAreas]} as BirthInfo);
  useEffect(()=>{
    const stored=loadBirth();
    // 从浏览器会话恢复一次填写进度。
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if(stored)setData(stored);
  },[]);
  useEffect(()=>{saveJson(STORAGE.birth,data)},[data]);
  const provinces=Object.keys(CN_LOCATIONS); const cities=CN_LOCATIONS[data.birthProvince]||[];
  const update=<K extends keyof BirthInfo>(key:K,value:BirthInfo[K])=>setData(d=>({...d,[key]:value}));
  const validate=()=>{setError("");if(step===1&&!data.gender){setError("请选择性别后继续。");return false}if(step===2){const date=new Date(Date.UTC(data.birthYear,data.birthMonth-1,data.birthDay));if(data.calendarType==="solar"&&(date.getUTCFullYear()!==data.birthYear||date.getUTCMonth()!==data.birthMonth-1||date.getUTCDate()!==data.birthDay)){setError("日期似乎不存在，请重新检查。");return false}if(data.calendarType==="lunar"&&data.birthDay>30){setError("农历日期最多为三十。");return false}}if(step===3){if(data.timeAccuracy==="shichen"&&!data.birthShichen){setError("请选择大概时辰。");return false}if(data.timeAccuracy==="period"&&!data.birthPeriod){setError("请选择大概时间段。");return false}}if(step===4&&(!data.birthCountry.trim()||!data.birthProvince.trim()||!data.birthCity.trim())){setError("出生地点似乎没有填写完整。");return false}return true};
  const next=()=>{if(validate())setStep(s=>Math.min(5,s+1))};
  const submit=()=>{const result=birthInfoSchema.safeParse(data);if(!result.success){setError(result.error.issues[0]?.message||"请检查填写内容。");return}if(!data.disclaimerAccepted){setError("请阅读并勾选文化体验说明。");return}saveJson(STORAGE.birth,data);sessionStorage.removeItem(STORAGE.sample);sessionStorage.removeItem(STORAGE.chart);sessionStorage.removeItem(STORAGE.report);router.push("/generating")};
  const summary=useMemo(()=>({gender:data.gender==="male"?"男":"女",date:`${data.birthYear} 年 ${data.birthMonth} 月 ${data.birthDay} 日${data.calendarType==="lunar"?(data.isLeapMonth?"（闰月）":"（农历）"):"（公历）"}`,time:data.timeAccuracy==="exact"?`${String(data.birthHour).padStart(2,"0")}:${String(data.birthMinute).padStart(2,"0")}`:data.timeAccuracy==="shichen"?SHICHEN.find(x=>x[0]===data.birthShichen)?.[1]||"未选择":data.timeAccuracy==="period"?PERIODS.find(x=>x[0]===data.birthPeriod)?.[1]||"未选择":"完全未知",location:`${data.birthCountry} · ${data.birthProvince} · ${data.birthCity}`}),[data]);
  return <main className="app-shell paper-grain"><PageHeader title="命盘探索"/><div className="form-top"><div><b>命盘探索 {step} / 5</b><span>每一步都可以返回修改</span></div><div className="progress"><i style={{width:`${step*20}%`}}/></div></div>
    <div className="content form-content"><AnimatePresence mode="wait"><motion.section key={step} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={{duration:.2}}>
      {step===1&&<Step title="先认识一下你" copy="该信息仅用于传统命理排盘规则。" icon={<UserRound/>}><div className="choice-grid two">{(["male","female"] as Gender[]).map(g=><Choice key={g} active={data.gender===g} onClick={()=>update("gender",g)} title={g==="male"?"男":"女"} />)}</div></Step>}
      {step===2&&<Step title="你的出生日期" copy="公历和农历的计算方式不同，请按实际记录选择。" icon={<CalendarDays/>}><div className="segment">{(["solar","lunar"] as CalendarType[]).map(x=><button key={x} className={data.calendarType===x?"active":""} onClick={()=>update("calendarType",x)}>{x==="solar"?"公历":"农历"}</button>)}</div><div className="date-fields"><Field label="出生年份"><input type="number" min="1900" max={new Date().getFullYear()} value={data.birthYear} onChange={e=>update("birthYear",+e.target.value)}/></Field><Field label="月份"><select value={data.birthMonth} onChange={e=>update("birthMonth",+e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1}>{i+1}</option>)}</select></Field><Field label="日期"><select value={data.birthDay} onChange={e=>update("birthDay",+e.target.value)}>{Array.from({length:data.calendarType==="lunar"?30:31},(_,i)=><option key={i+1}>{i+1}</option>)}</select></Field></div>{data.calendarType==="lunar"&&<label className="checkline"><input type="checkbox" checked={data.isLeapMonth} onChange={e=>update("isLeapMonth",e.target.checked)}/><span>这是闰月</span></label>}<Mascot text="公历和农历要选准确哦，它们的计算方式并不一样。"/></Step>}
      {step===3&&<Step title="你记得出生时间吗？" copy="越准确，命盘中的时柱和部分细节越有参考价值。" icon={<Clock3/>}><div className="accuracy-list">{(["exact","shichen","period","unknown"] as TimeAccuracy[]).map(x=><Choice key={x} active={data.timeAccuracy===x} onClick={()=>update("timeAccuracy",x)} title={{exact:"记得准确时间",shichen:"只记得大概时辰",period:"只记得大概时间段",unknown:"完全不记得"}[x]} desc={{exact:"精确到时、分",shichen:"十二时辰范围",period:"如上午、下午",unknown:"仅生成三柱基础报告"}[x]}/>)}</div>{data.timeAccuracy==="exact"&&<div className="time-fields"><Field label="小时"><select value={data.birthHour} onChange={e=>update("birthHour",+e.target.value)}>{Array.from({length:24},(_,i)=><option key={i}>{String(i).padStart(2,"0")}</option>)}</select></Field><Field label="分钟"><select value={data.birthMinute} onChange={e=>update("birthMinute",+e.target.value)}>{Array.from({length:60},(_,i)=><option key={i}>{String(i).padStart(2,"0")}</option>)}</select></Field></div>}{data.timeAccuracy==="shichen"&&<div className="option-scroll">{SHICHEN.map(x=><button key={x[0]} className={data.birthShichen===x[0]?"active":""} onClick={()=>update("birthShichen",x[0])}><b>{x[1]}</b><span>{x[2]}</span></button>)}</div>}{data.timeAccuracy==="period"&&<div className="option-scroll period">{PERIODS.map(x=><button key={x[0]} className={data.birthPeriod===x[0]?"active":""} onClick={()=>update("birthPeriod",x[0])}><b>{x[1]}</b><span>{x[2]}</span></button>)}</div>}{data.timeAccuracy==="unknown"&&<p className="warning">由于出生时间不确定，时柱、大运起算以及依赖时辰的部分内容可能存在明显偏差。本报告将减少相关判断，并标注为低置信度内容。</p>}<Mascot text="只记得大概时辰也没关系，我会把不确定性写进报告里。"/></Step>}
      {step===4&&<Step title="你在哪里出生？" copy="出生地点用于确定时区，并在启用真太阳时选项时辅助时间修正。" icon={<MapPin/>}><div className="segment"><button className={data.birthCountry==="中国"?"active":""} onClick={()=>setData(d=>({...d,birthCountry:"中国",birthProvince:"浙江省",birthCity:"宁波市",timezone:"Asia/Shanghai"}))}>中国大陆</button><button className={data.birthCountry!=="中国"?"active":""} onClick={()=>setData(d=>({...d,birthCountry:"",birthProvince:"",birthCity:"",timezone:"UTC"}))}>海外地区</button></div>{data.birthCountry==="中国"?<><Field label="省份"><select value={data.birthProvince} onChange={e=>setData(d=>({...d,birthProvince:e.target.value,birthCity:CN_LOCATIONS[e.target.value][0]}))}>{provinces.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="城市"><select value={data.birthCity} onChange={e=>update("birthCity",e.target.value)}>{cities.map(x=><option key={x}>{x}</option>)}</select></Field></>:<><Field label="国家 / 地区"><input value={data.birthCountry} maxLength={40} placeholder="例如：美国" onChange={e=>update("birthCountry",e.target.value)}/></Field><Field label="省份 / 州"><input value={data.birthProvince} maxLength={60} placeholder="例如：California" onChange={e=>update("birthProvince",e.target.value)}/></Field><Field label="城市"><input value={data.birthCity} maxLength={60} placeholder="例如：Los Angeles" onChange={e=>update("birthCity",e.target.value)}/></Field><Field label="IANA 时区"><input value={data.timezone} maxLength={64} placeholder="例如：America/Los_Angeles" onChange={e=>update("timezone",e.target.value)}/></Field></>}<label className="switchline"><span><b>使用真太阳时修正</b><small>实验功能，需要可靠经度</small></span><input type="checkbox" checked={data.useTrueSolarTime} onChange={e=>update("useTrueSolarTime",e.target.checked)}/></label>{data.useTrueSolarTime&&<Field label="出生地经度"><input type="number" value={data.longitude??""} placeholder="例如：121.55" onChange={e=>update("longitude",e.target.value?+e.target.value:undefined)}/></Field>}<p className="warning"><Globe2 size={16}/> 第一版采用当地标准时间。只有填写可靠经度后才会启用真太阳时选项，不会假装完成修正。</p></Step>}
      {step===5&&<Step title="最后，想重点了解什么？" copy="最多选择三个，只影响报告篇幅，不改变基础命盘计算。" icon={<Check/>}><div className="focus-grid">{FOCUS_AREAS.map(x=><button key={x} className={data.focusAreas.includes(x)?"active":""} onClick={()=>{const has=data.focusAreas.includes(x);update("focusAreas",has?data.focusAreas.filter(a=>a!==x):data.focusAreas.length<3?[...data.focusAreas,x]:data.focusAreas)}}>{data.focusAreas.includes(x)&&<Check size={15}/>} {x}</button>)}</div><div className="summary-card"><h3>信息确认</h3>{[["性别",summary.gender,1],["出生日期",summary.date,2],["出生时间",summary.time,3],["时间准确度",timeLabels[data.timeAccuracy],3],["出生地点",summary.location,4],["关注方向",data.focusAreas.join("、")||"未特别选择",5]].map(([k,v,s])=><div key={k as string}><span>{k}</span><b>{v}</b><button aria-label={`修改${k}`} onClick={()=>setStep(Number(s))}><Pencil size={14}/></button></div>)}</div><div className="disclaimer-box"><p>{DISCLAIMER}</p><label className="checkline"><input type="checkbox" checked={data.disclaimerAccepted} onChange={e=>update("disclaimerAccepted",e.target.checked)}/><span>我已阅读并理解：本报告仅供传统文化体验和自我探索参考，不属于科学预测，也不应作为重大人生决策依据。</span></label></div></Step>}
    </motion.section></AnimatePresence>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions">{step>1&&<button className="secondary-button" onClick={()=>{setError("");setStep(s=>s-1)}}><ArrowLeft size={17}/> 上一步</button>}{step<5?<button className="primary-button" onClick={next}>下一步 <ArrowRight size={17}/></button>:<button className="primary-button" disabled={!data.disclaimerAccepted} onClick={submit}>生成分析报告 <ArrowRight size={17}/></button>}</div></div>
  </main>
}
function Step({title,copy,icon,children}:{title:string;copy:string;icon:React.ReactNode;children:React.ReactNode}){return <div><div className="step-heading"><span>{icon}</span><div><h1>{title}</h1><p>{copy}</p></div></div>{children}</div>}
function Choice({active,onClick,title,desc}:{active:boolean;onClick:()=>void;title:string;desc?:string}){return <button className={`choice ${active?"active":""}`} onClick={onClick}><span>{active&&<Check size={15}/>}</span><div><b>{title}</b>{desc&&<small>{desc}</small>}</div></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
